name: model_training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: cml_run
      - name: Train model
        env:
	    repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          pip install -r requirements.txt
          python train.py

          echo "MODEL METRICS"
          cat metrics.txt