name: model_training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v4
      #   with:
      #      python-version: '3.x'
      # - uses: iterative/setup-cml@v1
      - name: TrainModel
        env:
           repo_token: ${{secrets.GITHUB_TOKEN}}
        run: |
          python -m pip install -r requirements.txt
          python train.py
