name: model_training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/setup-python@v4
        with:
           python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
           repo_token: ${{secrets.GITHUB_TOKEN}}
        run:
          python -m pip install -r requirements.txt
          python train.py
